const mongoose=require("mongoose");
const orderschema=new mongoose.Schema({
    shippinginfo:{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        pincode:{
            type:Number,
            required:true
        },
        phoneno:{
            type:Number,
            required:true
        }
    },
    orderitems:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            product:{
                type:mongoose.Schema.ObjectId,
                ref:"product",
                required:true
            }
        }
    ],
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"user",
        required:true
    },
    paymentinfo:{
        id:{
        type:String,
        required:true
        },
        status:{
            type:String,
            required:true
        },
    },
    paidat:{
        type:Date,
        required:true,
        default:Date.now()
    },
    itemsprice:{
        type:Number,
        required:true,
        default:0
    },
    taxprice:{
        type:Number,
        required:true,
        default:0
    },
    shippingprice:{
        type:Number,
        required:true,
        default:0
    },
    totalprice:{
        type:Number,
        required:true,
        default:0
    },
    orderstatus:{
        type:String,
        required:true,
        default:"Processing"
    },
    deliveredat:{
        type:Date
    },
    createdat:{
        type:Date,
        default:Date.now()
    }
})
const order=new mongoose.model("orderlist",orderschema);
module.exports=order;